spring:
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    time-zone: Asia/Taipei
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/PVS
    username: pvs-backend
    password: HappyTeamMem6er5LoveTar0t
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 9100
  servlet:
    context-path: /pvs

webClient:
  baseUrl:
    sonar: "http://140.124.181.143:9002/api"
    github: "https://api.github.com/graphql"
    test: ""

springfox:
  documentation:
    open-api:
      enabled: true

message:
  exception: "exception error"
  success: "你成功了!"
  fail: "你失敗了!"
  invalid:
    url: "你連URL都不會打嗎?"
